name: Checkstyle and Tests

on:
  pull_request:
    branches:
      - 'main'
    types: [opened, synchronize, reopened]

jobs:
  test:
    name: Checkstyle and Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'semeru'
      - name: Change timezone
        run: |
          sudo timedatectl set-timezone Asia/Kolkata
      - name: Download MQ Source Connector JAR
        run: |
          curl -L -o kafka-connect-mq-source-2.1.0.jar https://github.com/ibm-messaging/kafka-connect-mq-source/releases/download/v2.1.0/kafka-connect-mq-source-2.1.0.jar

      - name: Install MQ Source Connector JAR in local Maven repository
        run: |
          mvn install:install-file \
            -Dfile=kafka-connect-mq-source-2.1.0.jar \
            -DgroupId=com.ibm.eventstreams.connect \
            -DartifactId=kafka-connect-mq-source \
            -Dversion=2.1.0 \
            -Dpackaging=jar
      - name: Get java-version
        run: |
          BUILD_VERSION=$( mvn help:evaluate -Dexpression=project.version -q -DforceStdout )
          echo "VERSION=$BUILD_VERSION" >> $GITHUB_ENV
      - name: Compile
        run: mvn -X compile
      - name: Checkstyle
        run: mvn -X validate
      - name: Test
        run: mvn -X test
  verify-commits:
    name: Verify Commits
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0

    - name: Verify Signed-off-by
      run: |
        for commit in $(git rev-list --no-merges HEAD^..HEAD); do
          if ! git log -1 --format=%B "$commit" | grep -q "^Signed-off-by: "; then
            echo "Commit $commit is missing Signed-off-by line."
            exit 1
          fi
        done